services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    depends_on:
      - chroma
  chroma:
    build:
      context: .
      dockerfile: Dockerfile.chroma
    ports:
      - 8000:8000
