services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    environment:
        - OPENAI_API_KEY=$OPENAI_API_KEY
    depends_on:
      - chroma
  chroma:
    build:
      context: .
      dockerfile: Dockerfile.chroma
    ports:
      - 8000:8000
